### ISSUE TITLE
OSX build

### ISSUE THREAD

**Issue by Tobias-Fischer** [conda-forge/ogre-feedstock#19]
Hi there,
Is there any way to build ogre for OSX? It would be great if it were useable there, too. Let me know if I can contribute somehow.

Best, Tobias

**Comment by wolfv** [comment]
Hi Tobias, 

I think it should be possible, and it should not be too difficult. I just don't have an OS X right now. If you want to give it a shot, feel free. Let me know if you need help setting up a local build environment.
