### ISSUE TITLE
Ogre 1.9.0 Version

### ISSUE THREAD

**Issue by smnemeth** [conda-forge/ogre-feedstock#31]
Is there any interest in having an ogre-1.9.0 version available?

The reason I ask is we have a need to use the 1.9.0 version as a third party application needs to use that version and build against it.  So I have a 1.9.0 recipe that I'm building against conda-forge and it works.  It may help other folks that need this version as well.

Thanks for considering this request.

**Comment by wolfv** [comment]
Hey, yes, you're very welcome to make a PR. If everything is green I will merge or create a new back port branch for 1.9.0.

Cheers!

**Comment by smnemeth** [comment]
So haven't I worked in a feedstock yet.  Sorry to ask dumb questions, but is there a process out there that can tell be what I need to do?

I just confirmed the SampleBrowser works, and I linked it up to my third party app--it displayed 3D visuals as expected.  This ogre build is much more complicated than the newer versions.  Part of the reason is because we need so many lower level OpenGL and X libraries.  To top it off, third party apps need to be able to include and link correctly with it.

CMake has not been my friend working with Ogre.  This build has around 10 patches that get applied to make it build and work correctly.  I could never get CMake to search the right paths, even though I defined them.  So the build.sh has a ton of -D options for all the include and library paths needed. 

I also needed to build another new package called libOIS, so that recipe will need to be pulled as well.  It seems this would be a new package.

A while ago I tried using the Xorg conda packages, but that did not work at the end of the day.  So I went back to using only CDT build packages.  It's rather unclear to me on how to use all the Xorg and CDT packages in Conda, if anyone has advice on this I would love to hear it.

Simple question, is it ok to only be available on linux?  I know nothing about how to do this on Windows or OSX.

**Comment by wolfv** [comment]
I think the best is to clone this repository, insert your recipe and make a PR. I'm happy to provide you feedback then!

If you really need libois then you first need to upload this to [staged-recipes](https://github.com/conda-forge/staged-recipes).

I agree, the CDT / XOrg situation is confusing, and unfortunately I also don't completely get it... I am just trying things until they work :/ 
We have a gitter channel where you can ask questions as well: https://gitter.im/conda-forge/conda-forge.github.io

Looking forward to the PR and feel free to ping me on staged-recipes!

**Comment by Tobias-Fischer** [comment]
Hi @smnemeth,
Do you still have plans to pursue this further?

**Comment by smnemeth** [comment]
Yes, I just have to get approval from my job first.

**Comment by Tobias-Fischer** [comment]
It's been a long while - PRs are still welcome, but closing here due to inactivity.
