### ISSUE TITLE
Ogre 1.10 vs 1.12 package size

### ISSUE THREAD

**Issue by traversaro** [conda-forge/ogre-feedstock#35]
While looking into https://github.com/robotology/gym-ignition/issues/279, I noticed that the size of Ogre 1.10 is quite different from the one of 1.12 (see https://anaconda.org/conda-forge/ogre/files), something like 10 MB (1.12) vs 100 MB (1.10). 
I checked, and most of the difference is in the shared directory:
![share_resources](https://user-images.githubusercontent.com/1857049/107438518-e2a50580-6b30-11eb-965c-1212a7b5af82.PNG)

I wonder if something is missing in 1.12, or on the other hand there is something we can remove (or move to a different output) in 1.10 .

**Comment by traversaro** [comment]
I wonder if this is related to https://github.com/RoboStack/ros-galactic/issues/24 .

**Comment by traversaro** [comment]
Possibly related to https://github.com/conda-forge/assimp-feedstock/issues/18 .

**Comment by Tobias-Fischer** [comment]
I think we can close here - we do not support 1.12 anymore.
