### ISSUE TITLE
Ogre 1.12 overlinking Accelerate framework?

### ISSUE THREAD

**Issue by traversaro** [conda-forge/ogre-feedstock#39]
In https://github.com/conda-forge/libignition-sensors-feedstock/pull/3 we experienced test failures when running tests that were linking Ogre 1.12 : 
~~~
 7/32 Test  #7: UNIT_Lidar_TEST .............................Subprocess aborted***Exception:   1.66 sec
dyld: Library not loaded: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
  Referenced from: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
  Reason: Incompatible library version: vecLib requires version 1.0.0 or later, but libBLAS.dylib provides version 0.0.0
~~~ 

The reason was not investigated fully, but it seems related to this change in Ogre upstream: https://github.com/OGRECave/ogre/pull/1513/files , that changed the system frameworks that are linked.

**Comment by Tobias-Fischer** [comment]
Closing here as not using 1.12 anymore
